openapi: "3.0.0"
info:
  title: Model for reinforcement learning API
  version: '0.1'
paths:
  /init:
    get:
      operationId: main.init
      parameters: []
      responses:
        200:
          description: correctly initialized a new model
          content:
            text/plain:
              schema:
                type: string
        401:
          description: invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidRequest"
  /action:
    post:
      operationId: main.action
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                state:
                  $ref: "#/components/schemas/State"
      responses:
        200:
          description: action to take (0 wait, 1 switch - buy or sell)
          content:
            text/plain:
              schema:
                type: integer
        401:
          description: invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidRequest"
  /learn:
    post:
      operationId: main.learn
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                state:
                  $ref: "#/components/schemas/State"
                action:
                  type: integer
                next_state:
                  $ref: "#/components/schemas/State"
                reward:
                  type: number
                  format: float
      responses:
        200:
          description: loss after backpropagation step
          content:
            text/plain:
              schema:
                type: number
                format: float
        401:
          description: invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidRequest"
components:
  schemas:
    InvalidRequest:
      type: object
      properties:
        error:
          type: string
        details:
          type: string
    State:
      type: object
      properties:
        price:
          type: number
          format: float
        volume:
          type: number
          format: float
        rsi:
          type: number
          format: float
        macd:
          type: number
          format: float
        EMA_12:
          type: number
          format: float
        EMA_26:
          type: number
          format: float
        value_percent_in_account:
          type: number
          format: float
        value_percent_in_assets:
          type: number
          format: float
